In [1]:
import sys, os
project_root = r"C:/Users/Asia/Desktop/mocadr/MoviesRecommendations"
sys.path.insert(0, project_root)
import pandas as pd

data = pd.read_csv("C:/Users/Asia/Desktop/mocadr/MoviesRecommendations/data/ratings.csv")
data

,userId,movieId,rating,timestamp
0,1,1,4.0,964982703
1,1,3,4.0,964981247
2,1,6,4.0,964982224
3,1,47,5.0,964983815
4,1,50,5.0,964982931
...,...,...,...,...
100831,610,166534,4.0,1493848402
100832,610,168248,5.0,1493850091
100833,610,168250,5.0,1494273047
100834,610,168252,5.0,1493846352


In [35]:
import sys, os
project_root = r"C:/Users/Asia/Desktop/mocadr/MoviesRecommendations"
sys.path.insert(0, project_root)

from modules.train import train_nmf_model, train_svd1_model
from modules.predict import predict
import pandas as pd

model = train_nmf_model("C:/Users/Asia/Desktop/mocadr/MoviesRecommendations/data/ratings.csv")

#train_svd1_model("C:/Users/Asia/Desktop/mocadr/project/MoviesRecomendation/data/ratings.csv")

c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:17

r: 6


c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(


In [2]:
z_approx, u, m = model
print(z_approx)

[[3.9287415 3.425532  3.314249  ... 3.5205967 3.5201228 4.0273585]
 [3.9067004 3.4056935 3.29743   ... 3.497694  3.4985533 4.001162 ]
 [3.9028347 3.401541  3.294764  ... 3.4899883 3.492512  3.9933476]
 ...
 [3.9000235 3.3986478 3.290444  ... 3.4888935 3.4889364 3.9735944]
 [3.9059012 3.405115  3.296097  ... 3.4979625 3.498385  3.9993174]
 [3.9465208 3.4396453 3.3310664 ... 3.5298004 3.5331726 4.0340056]]


In [1]:
import sys, os
project_root = r"C:/Users/Asia/Desktop/mocadr/MoviesRecommendations"
sys.path.insert(0, project_root)
import pandas as pd
from modules.utils import build_rating_matrix

Z, u, m = build_rating_matrix("C:/Users/Asia/Desktop/mocadr/MoviesRecommendations/data/ratings.csv")

In [2]:
from sklearn.decomposition import TruncatedSVD
import numpy as np
from modules.predict import predict

svd = TruncatedSVD(n_components=min(Z.shape)-1, random_state=42)
svd.fit(Z)

cumvar = np.cumsum(svd.explained_variance_ratio_)
k = np.argmax(cumvar >= 0.90) + 1
print(k)

svd = TruncatedSVD(n_components=k, random_state=42)
svd.fit(Z)
Sigma2 = np.diag(svd.singular_values_)
VT = svd.components_
W = svd.transform(Z) / svd.singular_values_
H = np.dot(Sigma2, VT)
Z_approx = np.dot(W, H)

263


In [3]:

predict([Z_approx, u, m], "C:/Users/Asia/Desktop/mocadr/MoviesRecommendations/data/sample_test.csv", "C:/Users/Asia/Desktop/mocadr/MoviesRecommendations/data/preds.csv")

In [34]:
pred = predict([Z_approx, u, m], test_file="C:/Users/Asia/Desktop/mocadr/MoviesRecommendations/data/sample_test.csv")
test = pd.read_csv("C:/Users/Asia/Desktop/mocadr/MoviesRecommendations/data/sample_test_with_ratings.csv")
rss = (1 / len(test) * sum((pred["rating"] - test["rating"])**2))**(1/2)
print(rss)

0.2345207879911715


In [23]:
from numpy.linalg import svd

svd(Z)

SVDResult(U=array([[-0.04072622,  0.06485035, -0.00035679, ..., -0.00189233,
         0.00356444, -0.00040775],
       [-0.04048845, -0.00194645,  0.00602328, ...,  0.0006567 ,
        -0.00218156, -0.00589382],
       [-0.04043146, -0.01375114,  0.01321075, ...,  0.00052762,
        -0.00057212,  0.00048026],
       ...,
       [-0.04032848, -0.05109534, -0.15064354, ..., -0.00117985,
         0.00083818, -0.00117465],
       [-0.04047699, -0.0091175 , -0.0004431 , ..., -0.01180796,
        -0.00501826, -0.04002452],
       [-0.04086115,  0.11985665, -0.07935347, ..., -0.00142953,
        -0.00048871, -0.0002894 ]], shape=(610, 610), dtype=float32), S=array([8.23226758e+03, 5.11414070e+01, 4.05932541e+01, 3.95841446e+01,
       3.65124550e+01, 3.40626564e+01, 3.35997849e+01, 3.29047890e+01,
       3.19875851e+01, 3.14118938e+01, 3.06308689e+01, 2.96461563e+01,
       2.96407261e+01, 2.88323345e+01, 2.77973480e+01, 2.75347424e+01,
       2.71896324e+01, 2.68351078e+01, 2.65896702e+01, 

In [36]:
import sys, os
project_root = r"C:/Users/Asia/Desktop/mocadr/MoviesRecommendations"
sys.path.insert(0, project_root)

from modules.predict import predict

pred = predict(model, test_file = "C:/Users/Asia/Desktop/mocadr/MoviesRecommendations/data/sample_test.csv")

print(pred)

    userId  movieId  rating
0      432    77866     3.0
1      288      474     3.5
2      599     4351     3.0
3       42     2987     3.5
4       75     1610     4.0
..     ...      ...     ...
95     279   164179     4.0
96     428     6365     3.5
97     152      858     4.5
98     328     1198     4.0
99     427      435     2.5

[100 rows x 3 columns]


In [37]:
test = pd.read_csv("C:/Users/Asia/Desktop/mocadr/MoviesRecommendations/data/sample_test_with_ratings.csv")
print(test)

    userId  movieId  rating
0      432    77866     4.5
1      288      474     3.0
2      599     4351     3.0
3       42     2987     4.0
4       75     1610     4.0
..     ...      ...     ...
95     279   164179     4.0
96     428     6365     3.0
97     152      858     5.0
98     328     1198     5.0
99     427      435     3.0

[100 rows x 3 columns]


In [38]:
rss = (1 / len(test) * sum((pred["rating"] - test["rating"])**2))**(1/2)

print(rss)

0.812403840463596


In [16]:
import sys, os
project_root = r"C:/Users/Asia/Desktop/mocadr/MoviesRecommendations"
sys.path.insert(0, project_root)

import pandas as pd
from sklearn.model_selection import KFold
from modules.predict import predict
from modules.utils import build_rating_matrix
from sklearn.decomposition import NMF
import numpy as np

df = pd.read_csv("C:/Users/Asia/Desktop/mocadr/MoviesRecommendations/data/ratings.csv")

folds = KFold(n_splits = 5, shuffle = True, random_state = 42)

n = 3
rss = {}
while n <= 13:
    print(n)
    rss_n = []
    for train_idx, test_idx in folds.split(df):
        train_df = df.iloc[train_idx].copy()
        test_df = df.iloc[test_idx].copy()

        Z_train, user_map_train, movie_map_train = build_rating_matrix(df = train_df)

        model = NMF(n_components = n, init = 'random', random_state = 0, max_iter = 1000)
        W = model.fit_transform(Z_train)
        H = model.components_
        Z_approx = np.dot(W, H)

        Z_pred = predict([Z_approx, user_map_train, movie_map_train], df = test_df.drop(columns=["rating"]))

        rss_n.append(np.sum((test_df["rating"] - Z_pred["rating"])**2))
    rss[n] = np.mean(rss_n)
    print(rss[n])
    n += 1

3
19555.4
4
19555.4
5
19555.4
6
19555.4
7


c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:17

19288.25
8


c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:17

19240.35
9


c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:17

19246.05
10


c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:17

19221.35
11


c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:17

19228.8
12


c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:17

19234.0
13


c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:1720: ConvergenceWarning: Maximum number of iterations 1000 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\Asia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\decomposition\_nmf.py:17

19194.65
